"""Trust boundary and source policy checks.

Source classes:
- local_state     -- SQLite/session state generated by ensemble-mcp
- client_input    -- MCP tool arguments from AI clients
- filesystem_scan -- project files, skill files, parser inputs

Policy:
- Persisted text is redacted before storage (common secret patterns)
- Parser failures never crash tool calls; return partial data
- Destructive operations (reset) require explicit confirmation
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from ..contracts.errors import ErrorCode, ToolError


class SourceClass(StrEnum):
    """Classification for data entering the system."""

    LOCAL_STATE = "local_state"
    CLIENT_INPUT = "client_input"
    FILESYSTEM_SCAN = "filesystem_scan"


def require_confirmation(
    confirm: bool,
    operation: str = "reset",
) -> None:
    """Enforce explicit confirmation for destructive operations.

    Raises ``ToolError`` with VALIDATION_CONSTRAINT if *confirm* is
    not ``True``.
    """
    if confirm is not True:
        raise ToolError(
            code=ErrorCode.VALIDATION_CONSTRAINT,
            message=f"Destructive operation '{operation}' requires confirm=true",
            details={"operation": operation},
        )


def validate_string(
    value: Any,
    field_name: str,
    *,
    min_length: int = 1,
    max_length: int = 10_000,
) -> str:
    """Validate that *value* is a non-empty string within length bounds."""
    if not isinstance(value, str):
        raise ToolError(
            code=ErrorCode.VALIDATION_INVALID_TYPE,
            message=f"'{field_name}' must be a string, got {type(value).__name__}",
            details={"field": field_name, "got_type": type(value).__name__},
        )
    if len(value) < min_length:
        raise ToolError(
            code=ErrorCode.VALIDATION_MISSING_FIELD,
            message=f"'{field_name}' must be at least {min_length} characters",
            details={"field": field_name, "min_length": min_length},
        )
    if len(value) > max_length:
        raise ToolError(
            code=ErrorCode.VALIDATION_CONSTRAINT,
            message=f"'{field_name}' exceeds maximum length of {max_length}",
            details={"field": field_name, "max_length": max_length},
        )
    return value


def validate_positive_int(
    value: Any,
    field_name: str,
    *,
    min_value: int = 1,
    max_value: int = 1_000_000,
) -> int:
    """Validate that *value* is a positive integer within bounds."""
    if not isinstance(value, int) or isinstance(value, bool):
        raise ToolError(
            code=ErrorCode.VALIDATION_INVALID_TYPE,
            message=f"'{field_name}' must be an integer, got {type(value).__name__}",
            details={"field": field_name, "got_type": type(value).__name__},
        )
    if value < min_value or value > max_value:
        raise ToolError(
            code=ErrorCode.VALIDATION_CONSTRAINT,
            message=f"'{field_name}' must be between {min_value} and {max_value}",
            details={"field": field_name, "min": min_value, "max": max_value},
        )
    return value
