/* ensemble-mcp — mock data */

const MOCK = {
  health: {
    status: "ok",
    version: "0.1.0b7",
    server_name: "ensemble-mcp",
    db_size_bytes: 14_847_552,
    db_path: "~/.cache/ensemble-mcp/data.db",
    uptime_seconds: 284_113,
    model_dir: "~/.cache/ensemble-mcp/models",
    embedding_model: "all-MiniLM-L6-v2",
    embedding_dims: 384,
    avg_embedding_ms: 4.8,
  },

  summary: {
    pattern_count: 1427,
    pending_suggestions: 6,
    active_skills: 23,
    project_count: 8,
    drift_checks_30d: 312,
    session_count: 94,
    sessions_running: 2,
    sessions_completed: 71,
    calls_today: 1834,
    calls_7d: [412, 389, 445, 612, 528, 473, 1834],
    pattern_growth_30d: [12, 8, 15, 22, 19, 28, 31, 24, 18, 25, 33, 27, 19, 22, 35, 41, 29, 24, 38, 32, 29, 44, 37, 31, 28, 42, 39, 33, 26, 41],
    calls_by_hour: [2,1,0,0,1,3,8,24,68,142,198,231,187,212,245,287,198,143,98,67,45,32,18,7],
  },

  recentActivity: [
    { tool: "patterns_search",      project: "acme/api",            duration_ms: 7,   ts: "10:42:18", ok: true },
    { tool: "drift_check",          project: "acme/api",            duration_ms: 12,  ts: "10:42:12", ok: true },
    { tool: "context_compress",     project: "acme/web",            duration_ms: 4,   ts: "10:41:58", ok: true },
    { tool: "session_save",         project: "acme/api",            duration_ms: 3,   ts: "10:41:44", ok: true },
    { tool: "model_recommend",      project: "—",                    duration_ms: 1,   ts: "10:41:30", ok: true },
    { tool: "patterns_search",      project: "lynkbyte/dashboard",  duration_ms: 9,   ts: "10:40:51", ok: true },
    { tool: "skills_discover",      project: "lynkbyte/dashboard",  duration_ms: 112, ts: "10:40:22", ok: true },
    { tool: "project_query",        project: "lynkbyte/dashboard",  duration_ms: 24,  ts: "10:39:58", ok: true },
    { tool: "patterns_store",       project: "acme/api",            duration_ms: 8,   ts: "10:39:12", ok: true },
    { tool: "drift_check",          project: "tilt/backend",        duration_ms: 14,  ts: "10:38:44", ok: false },
    { tool: "session_load",         project: "tilt/backend",        duration_ms: 2,   ts: "10:38:30", ok: true },
    { tool: "patterns_search",      project: "acme/api",            duration_ms: 6,   ts: "10:37:55", ok: true },
    { tool: "context_prepare",      project: "acme/web",            duration_ms: 5,   ts: "10:37:12", ok: true },
    { tool: "skills_suggest",       project: "lynkbyte/dashboard",  duration_ms: 231, ts: "10:36:44", ok: true },
    { tool: "project_index",        project: "tilt/backend",        duration_ms: 1840,ts: "10:35:18", ok: true },
    { tool: "patterns_search",      project: "acme/web",            duration_ms: 7,   ts: "10:34:52", ok: true },
    { tool: "health",               project: "—",                    duration_ms: 1,   ts: "10:34:00", ok: true },
    { tool: "session_search",       project: "acme/api",            duration_ms: 11,  ts: "10:33:18", ok: true },
    { tool: "patterns_prune",       project: "—",                    duration_ms: 87,  ts: "10:30:12", ok: true },
    { tool: "project_snapshot",     project: "lynkbyte/dashboard",  duration_ms: 58,  ts: "10:28:44", ok: true },
  ],

  patterns: [
    { id: 142, name: "sqlite-wal-mode-for-dashboard-reads", category: "how-it-works",
      context: "Dashboard SQLite reads blocking MCP writes during long indexer runs.",
      approach: "Set PRAGMA journal_mode=WAL and open read-only connections with query_only=ON in the dashboard process.",
      outcome: "Reads no longer block writes. Indexer p95 dropped from 2.1s to 240ms.",
      project: "ensemble-mcp", match_count: 14, last_matched_at: "2026-04-21 09:12", token_count: 68 },
    { id: 141, name: "onnx-runtime-first-load-latency", category: "gotcha",
      context: "First patterns_search call after server restart takes ~400ms.",
      approach: "Warm the MiniLM model on server boot with a dummy embedding call.",
      outcome: "First-call latency now ~6ms, matches steady-state.",
      project: "ensemble-mcp", match_count: 9, last_matched_at: "2026-04-20 16:44", token_count: 51 },
    { id: 139, name: "idempotency-key-ttl-too-short", category: "decision",
      context: "Retries during long pipelines (>24h) were bypassing idempotency.",
      approach: "Raised default idempotency_key_ttl_hours from 24 to 48; exposed in settings.",
      outcome: "No reported double-writes in the past 60 days.",
      project: "ensemble-mcp", match_count: 4, last_matched_at: "2026-04-18 11:02", token_count: 44 },
    { id: 137, name: "drift-threshold-per-project", category: "trade-off",
      context: "Infra repos need looser drift bounds; SDK repos need stricter.",
      approach: "Set drift_threshold_aligned in .ensemble-mcp.toml per project instead of globally.",
      outcome: "Fewer false 'significant_drift' verdicts on migration-heavy PRs.",
      project: "acme/api", match_count: 22, last_matched_at: "2026-04-22 10:12", token_count: 59 },
    { id: 135, name: "pattern-text-redaction-for-tokens", category: "problem-solution",
      context: "Agents were storing patterns containing short-lived API tokens.",
      approach: "Added regex-based redaction in patterns_store before embedding + write.",
      outcome: "6 previously stored tokens rewritten. No new leaks detected in audit.",
      project: "ensemble-mcp", match_count: 3, last_matched_at: "2026-04-11 08:41", token_count: 47 },
    { id: 132, name: "cluster-threshold-0.75-is-stable", category: "decision",
      context: "Tuning cluster_similarity_threshold for skills_suggest.",
      approach: "Tested 0.65, 0.70, 0.75, 0.80. Kept 0.75 — best precision without losing real clusters.",
      outcome: "Suggestion acceptance rate up from 41% → 63%.",
      project: "ensemble-mcp", match_count: 11, last_matched_at: "2026-04-19 13:28", token_count: 55 },
    { id: 129, name: "zero-match-pattern-prune-90d", category: "discovery",
      context: "DB was growing ~400 patterns/month with low match rate.",
      approach: "Schedule patterns_prune weekly with max_age_days=90, zero match_count filter.",
      outcome: "DB stabilised at ~1.4k patterns. Search latency -22%.",
      project: "ensemble-mcp", match_count: 7, last_matched_at: "2026-04-15 22:10", token_count: 49 },
    { id: 127, name: "tailwind-v4-migration-import", category: "what-changed",
      context: "Tailwind v4 removed @tailwind base directive.",
      approach: "Replaced with @import \"tailwindcss\" and rebuilt the design token layer.",
      outcome: "Build works. Watch out: dark: variants now need .dark class on html not body.",
      project: "acme/web", match_count: 18, last_matched_at: "2026-04-22 09:05", token_count: 53 },
    { id: 124, name: "aiohttp-pragma-query-only", category: "how-it-works",
      context: "Enforcing read-only on dashboard endpoints.",
      approach: "Open connection with detect_types=0 and run 'PRAGMA query_only = ON' on acquire.",
      outcome: "All write attempts from dashboard now fail fast with SQLITE_READONLY.",
      project: "ensemble-mcp", match_count: 5, last_matched_at: "2026-04-14 17:20", token_count: 41 },
    { id: 121, name: "mtime-cache-skills-discover", category: "how-it-works",
      context: "skills_discover was re-embedding unchanged files on every call.",
      approach: "Cache (path, mtime, embedding) in sqlite; skip if mtime unchanged.",
      outcome: "Repeated calls went from 380ms → 12ms on 40-file skill library.",
      project: "ensemble-mcp", match_count: 13, last_matched_at: "2026-04-22 08:44", token_count: 58 },
    { id: 118, name: "session-optimistic-version-conflict", category: "gotcha",
      context: "Concurrent session_save calls were silently overwriting.",
      approach: "Require explicit version param; return CONFLICT_VERSION_MISMATCH if stale.",
      outcome: "Checkpoint integrity preserved; agents handle conflict with reload+retry.",
      project: "acme/api", match_count: 6, last_matched_at: "2026-04-19 14:33", token_count: 61 },
    { id: 115, name: "suspicious-file-flag-migrations", category: "problem-solution",
      context: "drift_check ignored migrations that were unrelated to the task.",
      approach: "Added suspicious_patterns list (migration, schema, .env, package.json) — flag if path similarity < 0.3.",
      outcome: "Caught 4 out-of-scope migration PRs in the last sprint.",
      project: "tilt/backend", match_count: 8, last_matched_at: "2026-04-21 11:18", token_count: 64 },
  ],

  skillSuggestions: [
    { id: 11, proposed_name: "error-envelope-validation", pattern_ids: [142, 124, 118, 115],
      theme: "4 similar patterns about response envelope error handling in MCP tools.",
      confidence: 0.88, project: "ensemble-mcp" },
    { id: 10, proposed_name: "sqlite-indexer-mtime-cache", pattern_ids: [121, 142, 127],
      theme: "mtime-based caching for filesystem-backed embeddings.",
      confidence: 0.83, project: "ensemble-mcp" },
    { id: 9, proposed_name: "tailwind-v4-migration-checklist", pattern_ids: [127, 132],
      theme: "Tailwind v4 upgrade-time gotchas across 2 frontend projects.",
      confidence: 0.77, project: "acme/web" },
    { id: 8, proposed_name: "drift-threshold-tuning", pattern_ids: [137, 115],
      theme: "Per-project tuning of drift detection thresholds.",
      confidence: 0.74, project: "acme/api" },
    { id: 7, proposed_name: "idempotency-retry-semantics", pattern_ids: [139, 118],
      theme: "Idempotency key TTL and conflict resolution patterns.",
      confidence: 0.71, project: "ensemble-mcp" },
    { id: 6, proposed_name: "warming-onnx-models-at-boot", pattern_ids: [141, 121],
      theme: "Pre-warming ML models to avoid first-call latency.",
      confidence: 0.69, project: "ensemble-mcp" },
  ],

  trackedSkills: [
    { id: 22, name: "mcp-response-envelope",     path: ".ai/skills/mcp-response-envelope.md",       match_count: 84, last_matched: "2026-04-22 09:41", source: "opencode", stale: false },
    { id: 21, name: "sqlite-pragma-setup",       path: ".claude/skills/sqlite-pragma-setup.md",     match_count: 52, last_matched: "2026-04-21 22:10", source: "claude",   stale: false },
    { id: 20, name: "onnx-embedding-usage",      path: ".ai/skills/onnx-embedding-usage.md",        match_count: 41, last_matched: "2026-04-22 08:22", source: "opencode", stale: false },
    { id: 19, name: "drift-score-interpretation",path: ".ai/skills/drift-score-interpretation.md",  match_count: 33, last_matched: "2026-04-20 14:55", source: "opencode", stale: false },
    { id: 18, name: "pipeline-checkpoint-resume",path: ".ai/skills/pipeline-checkpoint-resume.md",  match_count: 28, last_matched: "2026-04-22 07:02", source: "opencode", stale: false },
    { id: 17, name: "python-async-aiohttp",      path: ".cursor/rules/python-async-aiohttp.md",     match_count: 19, last_matched: "2026-04-19 16:41", source: "cursor",   stale: false },
    { id: 16, name: "tailwind-v4-tokens",        path: ".ai/skills/tailwind-v4-tokens.md",          match_count: 14, last_matched: "2026-04-18 11:20", source: "opencode", stale: false },
    { id: 15, name: "old-deprecated-logger",     path: ".ai/skills/old-deprecated-logger.md",       match_count: 0,  last_matched: "2026-01-14 08:12", source: "opencode", stale: true },
    { id: 14, name: "legacy-settings-format",    path: ".claude/skills/legacy-settings-format.md",  match_count: 0,  last_matched: "2025-12-20 19:44", source: "claude",   stale: true },
  ],

  projects: [
    { path: "/Users/jsmith/code/acme/api",           name: "acme/api",
      files: 842, languages: { python: 612, yaml: 88, sql: 42, markdown: 66, toml: 24, dockerfile: 10 },
      patterns: 284, drift_checks: 142, sessions: 31, health: "healthy", stale: false,
      last_indexed: "2026-04-22 10:12", exports: 1864 },
    { path: "/Users/jsmith/code/acme/web",           name: "acme/web",
      files: 1284, languages: { typescript: 891, css: 122, scss: 84, json: 92, html: 35, markdown: 60 },
      patterns: 198, drift_checks: 88, sessions: 22, health: "healthy", stale: false,
      last_indexed: "2026-04-22 09:44", exports: 3412 },
    { path: "/Users/jsmith/code/lynkbyte/dashboard", name: "lynkbyte/dashboard",
      files: 412, languages: { typescript: 318, css: 42, markdown: 28, json: 24 },
      patterns: 89, drift_checks: 42, sessions: 12, health: "healthy", stale: false,
      last_indexed: "2026-04-22 10:34", exports: 984 },
    { path: "/Users/jsmith/code/tilt/backend",       name: "tilt/backend",
      files: 2104, languages: { go: 1684, yaml: 182, sql: 88, markdown: 110, dockerfile: 40 },
      patterns: 412, drift_checks: 188, sessions: 18, health: "stale", stale: true,
      last_indexed: "2026-04-18 14:12", exports: 5821, missing_files: 12 },
    { path: "/Users/jsmith/code/kiln/infra",         name: "kiln/infra",
      files: 318, languages: { terraform: 182, yaml: 88, markdown: 24, shell: 24 },
      patterns: 102, drift_checks: 61, sessions: 5, health: "healthy", stale: false,
      last_indexed: "2026-04-21 22:41", exports: 412 },
    { path: "/Users/jsmith/code/kiln/cli",           name: "kiln/cli",
      files: 184, languages: { rust: 142, toml: 24, markdown: 18 },
      patterns: 58, drift_checks: 34, sessions: 3, health: "healthy", stale: false,
      last_indexed: "2026-04-22 08:18", exports: 612 },
    { path: "/Users/jsmith/code/crystal/sdk",        name: "crystal/sdk",
      files: 642, languages: { typescript: 512, json: 84, markdown: 46 },
      patterns: 142, drift_checks: 72, sessions: 2, health: "healthy", stale: false,
      last_indexed: "2026-04-22 09:02", exports: 1884 },
    { path: "/Users/jsmith/code/ensemble-mcp",       name: "ensemble-mcp",
      files: 298, languages: { python: 242, markdown: 24, toml: 12, yaml: 12, html: 8 },
      patterns: 142, drift_checks: 18, sessions: 1, health: "healthy", stale: false,
      last_indexed: "2026-04-22 10:41", exports: 728 },
  ],

  drift: [
    { id: 412, project: "acme/api", ts: "2026-04-22 10:42:12",
      task_description: "Add cursor-based pagination to GET /orders",
      score: 0.18, similarity: 0.82, verdict: "aligned",
      changed_files: ["api/orders.py", "api/pagination.py", "tests/test_orders.py"],
      flags: [] },
    { id: 411, project: "acme/api", ts: "2026-04-22 09:14:02",
      task_description: "Fix N+1 query on order.line_items",
      score: 0.24, similarity: 0.76, verdict: "aligned",
      changed_files: ["api/orders.py", "api/queries.py"],
      flags: [] },
    { id: 410, project: "tilt/backend", ts: "2026-04-22 08:51:44",
      task_description: "Add rate limiting middleware to public endpoints",
      score: 0.47, similarity: 0.53, verdict: "minor_drift",
      changed_files: ["middleware/ratelimit.go", "config/redis.go", "migrations/0042_rate_limit.sql", "Dockerfile"],
      flags: ["Unexpected file change: migrations/0042_rate_limit.sql", "Unexpected file change: Dockerfile"] },
    { id: 409, project: "lynkbyte/dashboard", ts: "2026-04-22 07:42:10",
      task_description: "Improve settings page source-map visualization",
      score: 0.14, similarity: 0.86, verdict: "aligned",
      changed_files: ["src/pages/settings.tsx", "src/components/source-chip.tsx"],
      flags: [] },
    { id: 408, project: "acme/web", ts: "2026-04-21 22:08:44",
      task_description: "Migrate checkout page to Tailwind v4",
      score: 0.68, similarity: 0.32, verdict: "significant_drift",
      changed_files: ["pages/checkout.tsx", "tailwind.config.js", "package.json", "src/auth/session.ts", "server/db/schema.ts"],
      flags: ["Unexpected file change: package.json", "Unexpected file change: server/db/schema.ts", "Unrelated auth modifications"] },
    { id: 407, project: "acme/api", ts: "2026-04-21 18:44:10",
      task_description: "Return 422 for invalid idempotency keys",
      score: 0.22, similarity: 0.78, verdict: "aligned",
      changed_files: ["api/idempotency.py", "tests/test_idempotency.py"],
      flags: [] },
    { id: 406, project: "kiln/infra", ts: "2026-04-21 14:22:51",
      task_description: "Terraform: add staging VPC peering",
      score: 0.33, similarity: 0.67, verdict: "minor_drift",
      changed_files: ["terraform/staging/vpc.tf", "terraform/staging/peering.tf", ".env.example"],
      flags: ["Unexpected file change: .env.example"] },
    { id: 405, project: "acme/api", ts: "2026-04-21 11:58:02",
      task_description: "Deprecate legacy /v1/products endpoint",
      score: 0.21, similarity: 0.79, verdict: "aligned",
      changed_files: ["api/v1/products.py", "api/deprecation.py", "docs/api-v1.md"],
      flags: [] },
    { id: 404, project: "tilt/backend", ts: "2026-04-21 09:12:44",
      task_description: "Add prometheus metrics to worker pool",
      score: 0.52, similarity: 0.48, verdict: "minor_drift",
      changed_files: ["workers/pool.go", "metrics/prometheus.go", "config/prod.yaml"],
      flags: ["Unexpected file change: config/prod.yaml"] },
  ],

  sessions: [
    { session_id: "sess_7dK92xPq", status: "running", version: 3, created_at: "2026-04-22 10:22:14",
      original_request: "Add cursor pagination to GET /orders endpoint",
      task_classification: "standard", project: "acme/api",
      completed_steps: ["scope", "plan", "patterns_lookup"],
      remaining_steps: ["implement", "test", "review"],
      files_changed: ["api/orders.py", "api/pagination.py"],
      decisions: ["Use opaque cursor encoding b64(created_at||id)", "Cap page size at 100"],
      errors: [],
      state: { stage: "implement", model_tier: "mid", last_tool: "patterns_search" } },
    { session_id: "sess_3mQpZfL8", status: "running", version: 7, created_at: "2026-04-22 09:58:44",
      original_request: "Refactor auth middleware to support multi-tenant JWT",
      task_classification: "complex", project: "acme/api",
      completed_steps: ["scope", "plan", "patterns_lookup", "implement"],
      remaining_steps: ["test", "review"],
      files_changed: ["auth/middleware.py", "auth/tenant.py", "auth/jwt.py", "tests/test_auth.py"],
      decisions: ["Decode tenant from JWT 'tid' claim", "Fall back to subdomain for legacy tokens"],
      errors: [],
      state: { stage: "test", model_tier: "best", last_tool: "drift_check" } },
    { session_id: "sess_Kp2Lx0W9", status: "completed", version: 5, created_at: "2026-04-22 08:12:10",
      original_request: "Add dark mode toggle to dashboard",
      task_classification: "simple", project: "lynkbyte/dashboard",
      completed_steps: ["scope", "plan", "implement", "test", "review"],
      remaining_steps: [],
      files_changed: ["src/ThemeToggle.tsx", "src/theme.ts", "styles/globals.css"],
      decisions: ["CSS variables over class swap for theme"],
      errors: [],
      state: { stage: "done", model_tier: "cheapest" } },
    { session_id: "sess_V4nBxR2E", status: "failed", version: 4, created_at: "2026-04-22 07:42:22",
      original_request: "Migrate checkout page to Tailwind v4",
      task_classification: "standard", project: "acme/web",
      completed_steps: ["scope", "plan", "implement"],
      remaining_steps: ["test", "review"],
      files_changed: ["pages/checkout.tsx", "tailwind.config.js"],
      decisions: [],
      errors: ["drift_check returned significant_drift (score=0.68)", "Pipeline halted for manual review"],
      state: { stage: "blocked", model_tier: "mid" } },
    { session_id: "sess_H8qL2kWj", status: "completed", version: 6, created_at: "2026-04-21 22:08:44",
      original_request: "Add rate limiting to public endpoints",
      task_classification: "standard", project: "tilt/backend",
      completed_steps: ["scope", "plan", "implement", "test", "review"],
      remaining_steps: [],
      files_changed: ["middleware/ratelimit.go", "config/redis.go"],
      decisions: ["Token-bucket via Redis INCR + EXPIRE", "60 rpm anon, 600 rpm authed"],
      errors: [],
      state: { stage: "done", model_tier: "mid" } },
    { session_id: "sess_R9xQpTn2", status: "completed", version: 3, created_at: "2026-04-21 18:44:10",
      original_request: "Return 422 for invalid idempotency keys",
      task_classification: "simple", project: "acme/api",
      completed_steps: ["scope", "implement", "test"],
      remaining_steps: [],
      files_changed: ["api/idempotency.py", "tests/test_idempotency.py"],
      decisions: [],
      errors: [],
      state: { stage: "done", model_tier: "cheapest" } },
  ],

  settings: [
    { group: "Storage", key: "cache_dir", value: "~/.cache/ensemble-mcp", type: "path", source: "default",
      desc: "Directory for cache data (DB and models)", default: "~/.cache/ensemble-mcp" },
    { group: "Storage", key: "db_path", value: "~/.cache/ensemble-mcp/data.db", type: "path", source: "default",
      desc: "Path to the SQLite database file", default: "~/.cache/ensemble-mcp/data.db" },
    { group: "Storage", key: "model_dir", value: "~/.cache/ensemble-mcp/models", type: "path", source: "default",
      desc: "Directory for ONNX embedding model files", default: "~/.cache/ensemble-mcp/models" },

    { group: "Patterns", key: "max_patterns", value: 20000, type: "int", source: "global_config",
      desc: "Maximum number of stored patterns", default: 10000 },
    { group: "Patterns", key: "default_top_k", value: 5, type: "int", source: "global_config",
      desc: "Default number of results for pattern search", default: 3 },
    { group: "Patterns", key: "default_min_score", value: 0.3, type: "float", source: "default",
      desc: "Minimum similarity score for pattern matches", default: 0.3 },
    { group: "Patterns", key: "default_prune_max_age_days", value: 90, type: "int", source: "default",
      desc: "Default max age (days) for pruning stale patterns", default: 90 },

    { group: "Drift Detection", key: "drift_threshold_aligned", value: 0.2, type: "float", source: "project_config",
      desc: "Score threshold below which drift is 'aligned'", default: 0.3 },
    { group: "Drift Detection", key: "drift_threshold_minor", value: 0.5, type: "float", source: "project_config",
      desc: "Score threshold below which drift is 'minor'", default: 0.6 },

    { group: "Skills", key: "cluster_similarity_threshold", value: 0.75, type: "float", source: "default",
      desc: "Cosine similarity threshold for skill clustering", default: 0.75 },
    { group: "Skills", key: "default_min_cluster_size", value: 3, type: "int", source: "default",
      desc: "Minimum cluster size for skill suggestions", default: 3 },
    { group: "Skills", key: "default_stale_threshold_days", value: 60, type: "int", source: "default",
      desc: "Days before a skill is considered stale", default: 60 },

    { group: "Runtime", key: "idempotency_key_ttl_hours", value: 48, type: "int", source: "env",
      desc: "Hours before idempotency keys expire", default: 24 },
  ],
};

/* language colors */
const LANG_COLOR = {
  python: "#3572A5", typescript: "#3178C6", javascript: "#F7DF1E",
  go: "#00ADD8", rust: "#DEA584", php: "#4F5D95", ruby: "#701516",
  java: "#B07219", kotlin: "#A97BFF", swift: "#F05138",
  c: "#555555", "c++": "#F34B7D", "c#": "#178600",
  vue: "#41B883", svelte: "#FF3E00", html: "#E34C26",
  css: "#563D7C", scss: "#C6538C", less: "#1D365D",
  json: "#292929", yaml: "#CB171E", toml: "#9C4221", xml: "#0060AC",
  markdown: "#083FA1", sql: "#E38C00", shell: "#89E051",
  dockerfile: "#384D54", terraform: "#844FBA",
};
function langColor(name) { return LANG_COLOR[name?.toLowerCase?.()] || "#6366F1"; }

window.MOCK = MOCK;
window.langColor = langColor;
